# https://www.dartlang.org/guides/language/analysis-options
# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - valid_regexps
    - always_declare_return_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - one_member_abstracts
    - slash_for_doc_comments
    - unnecessary_brace_in_string_interps

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  exclude:
    - test/test.dart
    - test/echo_port.dart